name: gutils38
channels:
  - conda-forge
  - axiom-data-science
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - antlr-python-runtime=4.7.2
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=21.12b0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cc-plugin-glider=1.0.6
  - certifi=2021.10.8
  - cf-units=3.0.1
  - cffi=1.15.0
  - cftime=1.5.1.1
  - charset-normalizer=2.0.10
  - click=8.0.3
  - compliance-checker=4.3.4
  - cryptography=36.0.0
  - curl=7.81.0
  - dataclasses=0.8
  - decorator=5.1.1
  - executing=0.8.2
  - expat=2.4.2
  - flake8=4.0.1
  - geos=3.10.1
  - gsw=3.4.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=69.1
  - idna=3.1
  - importlib-metadata=4.2.0
  - iniconfig=1.1.1
  - ipdb=0.13.9
  - ipython=8.0.0
  - isodate=0.6.1
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9d
  - krb5=1.19.2
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.81.0
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzip=1.8.0
  - libzlib=1.2.11
  - lxml=4.7.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.3
  - mccabe=0.6.1
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - netcdf4=1.5.8
  - numpy=1.18.5
  - owslib=0.25.0
  - packaging=21.3
  - pandas=0.25.3
  - parso=0.8.3
  - pathspec=0.9.0
  - pendulum=2.1.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.3.1
  - platformdirs=2.3.0
  - pluggy=1.0.0
  - pocean-core=1.9.3
  - proj=8.2.1
  - prompt-toolkit=3.0.24
  - ptyprocess=0.7.0
  - pure_eval=0.2.1
  - py=1.11.0
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pyflakes=2.4.0
  - pygc=1.2.1
  - pygeoif=0.7
  - pygments=2.11.2
  - pyinotify=0.9.6
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyproj=3.3.0
  - pysocks=1.7.1
  - pytest=6.2.5
  - pytest-flake8=1.0.7
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - pytzdata=2020.1
  - pyyaml=6.0
  - readline=8.1
  - regex=2021.11.10
  - requests=2.27.1
  - scipy=1.7.3
  - setuptools=60.5.0
  - shapely=1.8.0
  - simplejson=3.17.6
  - six=1.16.0
  - sqlite=3.37.0
  - stack_data=0.1.3
  - tk=8.6.11
  - toml=0.10.2
  - tomli=1.2.2
  - traitlets=5.1.1
  - typed-ast=1.5.1
  - typing_extensions=4.0.1
  - udunits2=2.2.27.27
  - urllib3=1.26.8
  - validators=0.18.2
  - wcwidth=0.2.5
  - wheel=0.37.1
  - whichcraft=0.6.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.1
