name: gutils
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.3
  - antlr-python-runtime=4.7.2
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cc-plugin-glider=1.0.6
  - certifi=2021.10.8
  - cf-units=3.0.1
  - cffi=1.15.0
  - cfgv=3.3.1
  - cftime=1.6.0
  - charset-normalizer=2.0.12
  - compliance-checker=5.0.0
  - cryptography=36.0.0
  - curl=7.82.0
  - cycler=0.11.0
  - dbus=1.13.6
  - decorator=5.1.1
  - distlib=0.3.4
  - executing=0.8.3
  - expat=2.4.7
  - filelock=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.96
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.2
  - freetype=2.10.4
  - geos=3.10.2
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gsw=3.4.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=69.1
  - identify=2.4.11
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - iniconfig=1.1.1
  - ipdb=0.13.9
  - ipython=8.1.1
  - isodate=0.6.1
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcurl=7.82.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm13=13.0.1
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.18
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.2
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzip=1.8.0
  - libzlib=1.2.11
  - lxml=4.8.0
  - lz4-c=1.9.3
  - markupsafe=2.1.0
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - munkres=1.1.4
  - mysql-common=8.0.28
  - mysql-libs=8.0.28
  - ncurses=6.3
  - netcdf4=1.5.8
  - nodeenv=1.6.0
  - nspr=4.32
  - nss=3.74
  - numpy=1.22.3
  - openjpeg=2.4.0
  - openssl=1.1.1n
  - owslib=0.25.0
  - packaging=21.3
  - pandas=1.4.1
  - parso=0.8.3
  - pcre=8.45
  - pendulum=2.1.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.1.0
  - pip=22.0.4
  - platformdirs=2.5.1
  - pluggy=1.0.0
  - pocean-core=3.0.0
  - pre-commit=2.17.0
  - proj=9.0.0
  - prompt-toolkit=3.0.27
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pycparser=2.21
  - pygeoif=0.7
  - pygments=2.11.2
  - pyinotify=0.9.6
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyproj=3.3.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - pytest=7.1.0
  - python=3.9.10
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pytzdata=2020.1
  - pyyaml=6.0
  - qt=5.12.9
  - readline=8.1
  - regex=2022.3.2
  - requests=2.27.1
  - scipy=1.8.0
  - shapely=1.8.0
  - simplejson=3.17.6
  - six=1.16.0
  - sqlite=3.37.0
  - stack_data=0.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=4.2.0
  - tzdata=2021e
  - udunits2=2.2.28
  - ukkonen=1.0.1
  - unicodedata2=14.0.0
  - urllib3=1.26.8
  - validators=0.18.2
  - virtualenv=20.13.3
  - wcwidth=0.2.5
  - wheel=0.37.1
  - whichcraft=0.6.1
  - xarray=2022.3.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.5.2
