package:
    name: gutils
    version: "3.2.0"

source:
    path: ../

build:
    number: 0
    noarch: python
    script: python -m pip install --no-deps --ignore-installed .
    entry_points:
        - gutils_create_nc = gutils.nc:main_create
        - gutils_check_nc = gutils.nc:main_check
        - gutils_binary_to_ascii_watch = gutils.watch.binary:main_to_ascii
        - gutils_ascii_to_netcdf_watch = gutils.watch.ascii:main_to_netcdf
        - gutils_netcdf_to_ftp_watch = gutils.watch.netcdf:main_to_ftp
        - gutils_netcdf_to_erddap_watch = gutils.watch.netcdf:main_to_erddap

requirements:
    build:
        - python
        - pip
    run:
        - cc-plugin-glider >=1.0.4
        - compliance-checker >=4.1.1
        - gsw
        - netcdf4
        - numpy >=1.14
        - pandas
        - pocean-core >=1.5.0,<2.0
        - pyinotify
        - python
        - scipy
        - six
        - whichcraft
        - cftime ==1.0.1

test:
    imports:
        - gutils
        - gutils.ctd
        - gutils.yo
        - gutils.filters
        - gutils.nc
        - gutils.slocum

    commands:
        - gutils_create_nc --help
        - gutils_check_nc --help
        - gutils_binary_to_ascii_watch --help
        - gutils_ascii_to_netcdf_watch --help
        - gutils_netcdf_to_ftp_watch --help
        - gutils_netcdf_to_erddap_watch --help

about:
    home: https://github.com/SECOORA/GUTILS
    license: MIT License
    license_file: LICENSE
    summary: A set of Python utilities for reading, merging, and post processing Teledyne Webb Slocum Glider data
